authentication/urls.py
# authentication/urls.py
from django.urls import path
from . import views

app_name = 'authentication'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_view, name='login'),
    path('', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('post/<int:post_id>/', views.post_detail, name='post_detail'),
    path('post/<int:post_id>/add_comment/', views.add_comment, name='add_comment'),
    path('like/<int:post_id>/', views.like_post, name='like_post'),
    path('my-posts/', views.user_posts, name='user_posts'),
    path('create/', views.create_post, name='create_post'),
    path('edit/<int:id>/', views.edit_post, name='edit_post'),  # Edit post route
    path('delete/<int:id>/', views.delete_post, name='delete_post'),  # Delete post route
    path('share/<int:post_id>/', views.share_post_via_email, name='share_post_via_email'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls', namespace='authentication')),
    path('blog/', include('blog.urls')),  # Include the blog app URLs
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.urls import reverse  # Ensure reverse is imported
from taggit.managers import TaggableManager


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='blog_posts'
    )
    body = models.TextField()
    photo = models.ImageField(upload_to='blog_photos/', blank=True, null=True)  # Add photo field
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=2,
        choices=Status.choices,
        default=Status.DRAFT
    )
    tags = TaggableManager()


    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]
    
    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'post_id': self.id})
    
    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Comment by {self.author} on {self.post}'


class Like(models.Model):
    post = models.ForeignKey(
        'Post',
        on_delete=models.CASCADE,
        related_name='likes'
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='likes'
    )
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user} liked {self.post}'


class Share(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='shares'
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='shares'
    )
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user} shared {self.post}'

blog/forms.py
from django import forms
from .models import Post,Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'slug', 'body', 'photo', 'publish', 'status', 'tags']  # Include 'publish' field

    # You can also apply additional customizations if needed, like widgets for styling
    publish = forms.DateTimeField(
        widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}),  # Display datetime in a local input format
        required=True
    )

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']
        labels = {'body': ''}

blog/views.py
from django.shortcuts import render, get_object_or_404,redirect
from .models import Post,Like
from django.contrib.auth.decorators import login_required
from .forms import PostForm
from django.core.mail import send_mail
from django.conf import settings
from .forms import CommentForm
from taggit.models import Tag
from django.core.paginator import Paginator
from django.db.models import Count
@login_required
def post_list(request):
    tag_name = request.GET.get('tag')  # Get the tag from the query parameters
    posts = Post.objects.filter(status=Post.Status.PUBLISHED)  # Filter for published posts
    liked_posts = Like.objects.filter(user=request.user).values_list('post', flat=True)  # Get liked posts by the user

    # Filter posts by tag if a tag name is provided
    if tag_name:
        tag = Tag.objects.filter(name__iexact=tag_name).first()  # Case-insensitive search for the tag
        if tag:
            posts = posts.filter(tags=tag)

    posts = posts.annotate(
        num_comments=Count('comments'),
        num_likes=Count('likes'),
        num_shares=Count('shares')
    )

    # Pagination
    paginator = Paginator(posts, 5)  # Show 5 posts per page
    page_number = request.GET.get('page')  # Get the current page number from the URL
    page_obj = paginator.get_page(page_number)  # Get the posts for the current page

    return render(request, 'blog/list.html', {
        'posts': page_obj,
        'liked_posts': liked_posts,
        'tag_name': tag_name,
    })

@login_required
def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    comments = post.comments.all()
    new_comment = None

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.author = request.user  # Assign the current user as the author
            new_comment.save()
            return redirect('blog:post_detail', post_id=post.id)
    else:
        comment_form = CommentForm()

    return render(request, 'blog/detail.html', {
        'post': post,
        'comments': comments,
        'new_comment': new_comment,
        'comment_form': comment_form
    })

@login_required
def user_posts(request):
    tag_name = request.GET.get('tag')  # Get the tag from the query parameters
    posts = Post.objects.filter(author=request.user)

    # Filter posts by tag if a tag name is provided
    if tag_name:
        tag = Tag.objects.filter(name__iexact=tag_name).first()  # Case-insensitive search for the tag
        if tag:
            posts = posts.filter(tags=tag)

    # Paginate the posts
    paginator = Paginator(posts, 5)  # Show 5 posts per page
    page_number = request.GET.get('page')  # Get the page number from query parameters
    page_obj = paginator.get_page(page_number)

    return render(request, 'blog/user_posts.html', {'page_obj': page_obj})

@login_required
def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user  # Set the logged-in user as the author
            post.save()
            form.save_m2m()
            return redirect('blog:user_posts')  # Redirect to the user's posts page
    else:
        form = PostForm()
    return render(request, 'blog/create_post.html', {'form': form})

@login_required
def edit_post(request, id):
    post = get_object_or_404(Post, id=id, author=request.user)  # Ensure only the author can edit
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return redirect('blog:user_posts')
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/edit_post.html', {'form': form, 'post': post})

@login_required
def delete_post(request, id):
    post = get_object_or_404(Post, id=id, author=request.user)  # Ensure only the author can delete
    if request.method == "POST":
        post.delete()
        return redirect('blog:user_posts')
    return render(request, 'blog/delete_post_confirm.html', {'post': post})

def like_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)   
   # Check if the user has already liked the post
    existing_like = Like.objects.filter(post=post, user=request.user).first()
    
    if existing_like:
        # If the user has liked the post, remove the like (dislike action)
        existing_like.delete()
    else:
        # If the user hasn't liked the post, create a new like
        Like.objects.create(post=post, user=request.user)
    
    return redirect('blog:post_list')  # Redirect back to the post list page

def share_post_via_email(request, post_id):
    post = get_object_or_404(Post, id=post_id)

    if request.method == 'POST':
        recipient_email = request.POST.get('email')

        # Get the current user who is sharing the post
        current_user = request.user

        # Construct the email subject and body
        subject = f"Check out this blog post: {post.title}"
        body = f"Hi, \n\n{current_user.username} wanted to share this blog post with you:\n\n{post.title}\n\n{post.body}\n\n"
        body += f"Shared by: {current_user.username}\n\n"
        body += f"Read more at: {request.build_absolute_uri(post.get_absolute_url())}"

        # Send the email
        send_mail(
            subject,
            body,
            settings.EMAIL_HOST_USER, 
            [recipient_email], 
            fail_silently=False,
        )

        # Redirect back to the blog list page after sending the email
        return redirect('blog:post_list')

    return redirect('blog:post_list')  # If not POST, just redirect to the post list

@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user  # Ensure the author is set
            comment.save()
            return redirect('blog:post_detail', post_id=post.id)
    else:
        form = CommentForm()
    return render(request, 'blog/detail.html', {'post': post, 'form': form})

blog/templates/blog/create_post.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="form-container">
        <h2 class="form-header">Create New Blog Post</h2>
        <form method="post" enctype="multipart/form-data" class="create-post-form">
            {% csrf_token %}
            <div class="form-group">
                {{ form.as_p }}
            </div>
            <button type="submit" class="btn btn-primary"> Post</button>
            
        </form>
    </div>
    <a href="{% url 'blog:user_posts' %}">Back to my posts</a>
{% endblock %}

blog/templates/blog/delete_post_confirm.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="delete-confirmation">
        <h2>Are you sure you want to delete this post?</h2>
        <p><strong>{{ post.title }}</strong></p>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Yes, Delete</button>
            <a href="{% url 'blog:user_posts' %}" class="btn btn-secondary">Cancel</a>
        </form>
    </div>
{% endblock %}

blog/templates/blog/detail.html
{% extends "blog/base.html" %}
{% load static %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'blog/css/styles.css' %}">
<div class="back-links">
    <a href="{% url 'blog:post_list' %}" class="back-link">Back to all posts</a>
    <a href="{% url 'blog:user_posts' %}" class="back-link">Back to my posts</a>
</div>
<article>
    <h2>{{ post.title }}</h2>
    <p><small>Published {{ post.publish }} by {{ post.author }}</small></p>
    <p>{{ post.body|linebreaks }}</p>
</article>

<!-- Comment Section -->
<section class="comments">
    <h3>Comments</h3>
    {% for comment in post.comments.all %}
    <div class="comment">
        <p><strong>{{ comment.author.last_name  }} {{ comment.author.first_name  }}</strong> said:</p>
        <p>{{ comment.body }}</p>
    </div>
    {% empty %}
    <p>No comments yet. Be the first to comment!</p>
    {% endfor %}
    {% if user.is_authenticated %}
    <form method="post" action="{% url 'blog:post_detail' post.id %}">
      {% csrf_token %}
      {{ comment_form.as_p }}
      <button type="submit">Add Comment</button>
    </form>
  
    {% else %}
    <p>You must be logged in to comment.</p>
    {% endif %}
</section>
{% endblock %}

blog/templates/blog/edit_post.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="form-container">
        <h2 class="form-header">Edit Blog Post</h2>
        <form method="post" enctype="multipart/form-data" class="create-post-form">
            {% csrf_token %}
            <div class="form-group">
                {{ form.as_p }}
            </div>
            <button type="submit" class="btn btn-primary">Save Changes</button>
        </form>
    </div>
    <a href="{% url 'blog:user_posts' %}">Back to my posts</a>
{% endblock %}

blog/templates/blog/list.html
{% extends "blog/base.html" %}
{% load static %}

{% block title %}Blog - Post List{% endblock %}

{% block content %}
<div style="text-align: right; margin-top: 20px;">
  <a href="{% url 'blog:create_post' %}" id="create-blog-btn" style="padding: 10px 20px; background-color: #ed3978; color: white; 
            text-decoration: none; border-radius: 5px; cursor: pointer;">
     Create New Blog
  </a>
</div>

<h2>Blog Posts</h2>
{% if user.is_authenticated %}
  <p>Welcome, {{ user.username }}!</p>
{% else %}
  <p>You are not logged in.</p>
{% endif %}

<form method="get" action="{% url 'blog:post_list' %}" style="margin-bottom: 20px;">
  <input 
    type="text" 
    name="tag" 
    placeholder="Filter by tag" 
    value="{{ request.GET.tag }}" 
    style="padding: 5px; width: 250px; border: 1px solid #ccc; border-radius: 5px;">
  <button 
    type="submit" 
    style="padding: 5px 20px; background-color: #007BFF; color: white; border: none; border-radius: 5px; cursor: pointer;">
    Filter
  </button>
</form>

{% for post in posts %}
  <article class="article-item">
    <div class="post-photo">
      {% if post.photo %}
        <img src="{{ post.photo.url }}" alt="{{ post.title }}" class="post-img">
      {% else %}
        <img src="{% static 'default_image.jpg' %}" alt="Default image">
      {% endif %}
    </div>

    <div class="post-body">
      <h3><a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a></h3>
      <div class="post-info">
        <p>
          <small>
            {% if post.publish %}
              Published {{ post.publish|date:"F j, Y" }}
            {% endif %}
            {% if post.author %}
              by {{ post.author }}
            {% endif %}
          </small>
        </p>
        {% if post.status %}
          <p>Status: {{ post.get_status_display }}</p>
        {% endif %}
      </div>
      <!-- Tag Display -->
      {% if post.tags.exists %}
        <div class="post-tags">
          <strong>Tags:</strong>
          {% for tag in post.tags.all %}
            <a href="{% url 'blog:post_list' %}?tag={{ tag.name }}" class="tag">{{ tag.name }}</a>{% if not forloop.last %}, {% endif %}
          {% endfor %}
        </div>
      {% endif %}

      <p>
        {{ post.body|slice:150 }}{% if post.body|length > 150 %}...{% endif %}
        {% if post.body|length > 150 %}
          <a href="{% url 'blog:post_detail' post.id %}" class="read-more">Read More</a>
        {% endif %}
      </p>

      <!-- Display Comments, Likes, and Shares Counts -->
      <div class="post-actions">
        <p class="post-stats">
          <span class="comments-count">{{ post.num_comments }} Comments</span> |
          <span class="likes-count">{{ post.num_likes }} Likes</span> |
          <span class="shares-count">{{ post.num_shares }} Shares</span>
        </p>
        

        {% if post.id in liked_posts %}
          <a href="{% url 'blog:like_post' post.id %}" class="like-btn">
            <i class="fa fa-thumbs-down"></i> Dislike
          </a>
        {% else %}
          <a href="{% url 'blog:like_post' post.id %}" class="like-btn">
            <i class="fa fa-thumbs-up"></i> Like
          </a>
        {% endif %}
        <button type="button" class="btn btn-primary" id="share-btn" data-bs-toggle="modal" data-bs-target="#shareModal">
          <i class="fa fa-share-alt"></i> Share via Email
        </button>
        <!-- Modal -->
        <div class="modal fade" id="shareModal" tabindex="-1" aria-labelledby="shareModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="shareModalLabel">Share Post via Email</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <form method="POST" action="{% url 'blog:share_post_via_email' post.id %}">
                  {% csrf_token %}
                  <div class="mb-3">
                    <label for="email" class="form-label">Recipient's Email</label>
                    <input type="email" class="form-control" name="email" id="email" required placeholder="Enter recipient's email">
                  </div>
                  <button type="submit" class="btn btn-primary">
                    <i class="fa fa-share-alt"></i> Share via Email
                  </button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </article>
{% endfor %}

<!-- Pagination Controls -->
<div class="pagination">
  <span class="step-links">
    {% if posts.has_previous %}
      <a href="?page=1{% if tag_name %}&tag={{ tag_name }}{% endif %}">&laquo; first</a>
      <a href="?page={{ posts.previous_page_number }}{% if tag_name %}&tag={{ tag_name }}{% endif %}">previous</a>
    {% endif %}

    <span class="current">
      Page {{ posts.number }} of {{ posts.paginator.num_pages }}.
    </span>

    {% if posts.has_next %}
      <a href="?page={{ posts.next_page_number }}{% if tag_name %}&tag={{ tag_name }}{% endif %}">next</a>
      <a href="?page={{ posts.paginator.num_pages }}{% if tag_name %}&tag={{ tag_name }}{% endif %}">last &raquo;</a>
    {% endif %}
  </span>
</div>

{% endblock %}

blog/templates/blog/user_posts.html
{% extends "blog/base.html" %}
{% load static %}

{% block title %}My Blog Posts{% endblock %}

{% block content %}
<!-- Create New Blog button placed under the nav -->
<div style="text-align: right; margin-top: 20px;">
    <a href="{% url 'blog:create_post' %}" id="create-blog-btn" style="padding: 10px 20px; background-color: #ed3978; color: white; 
              text-decoration: none; border-radius: 5px; cursor: pointer;">
       Create New Blog
    </a>
</div>

<h2>My Blog Posts</h2>

<form method="get" action="{% url 'blog:user_posts' %}" style="margin-bottom: 20px;">
  <input 
    type="text" 
    name="tag" 
    placeholder="Filter by tag" 
    value="{{ request.GET.tag }}" 
    style="padding: 5px; width: 250px; border: 1px solid #ccc; border-radius: 5px;">
  <button 
    type="submit" 
    style="padding: 5px 20px; background-color: #007BFF; color: white; border: none; border-radius: 5px; cursor: pointer;">
    Filter
  </button>
</form>

{% if page_obj %}
  {% for post in page_obj %}
    <article class="article-item">
      <div class="post-photo">
        {% if post.photo %}
          <img src="{{ post.photo.url }}" alt="{{ post.title }}" class="post-img">
        {% else %}
          <img src="{% static 'default_image.jpg' %}" alt="Default image">
        {% endif %}
      </div>

      <div class="post-body">
        <h3><a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a></h3>
        <div class="post-info">
          <p>
            <small>
              {% if post.publish %}
                Published {{ post.publish|date:"F j, Y" }}
              {% endif %}
              {% if post.author %}
                by {{ post.author }}
              {% endif %}
            </small>
          </p>
          {% if post.status %}
            <p>Status: {{ post.get_status_display }}</p>
          {% endif %}
        </div>
        <!-- Tag Display -->
        {% if post.tags.exists %}
          <div class="post-tags">
            <strong>Tags:</strong>
            {% for tag in post.tags.all %}
              <a href="{% url 'blog:user_posts' %}?tag={{ tag.name }}" class="tag">{{ tag.name }}</a>{% if not forloop.last %}, {% endif %}
            {% endfor %}
          </div>
        {% endif %}
        <p>
          {{ post.body|slice:150 }}{% if post.body|length > 150 %}...{% endif %}
          {% if post.body|length > 150 %}
            <a href="{% url 'blog:post_detail' post.id %}" class="read-more">Read More</a>
          {% endif %}
        </p>

        <!-- Edit and Delete Buttons -->
        <div class="post-actions">
          <a href="{% url 'blog:edit_post' post.id %}" class="edit-btn" style="font-size: 15px; padding: 10px 10px; background-color: #007bff; color: white; text-decoration: none; border-radius: 5px;">
            Edit
          </a>
          <form method="POST" action="{% url 'blog:delete_post' post.id %}" style="display: inline;">
            {% csrf_token %}
            <button type="submit" style="font-size: 15px;padding: 10px 10px; background-color: #dc3545; color: white; text-decoration: none; border: none; border-radius: 5px; cursor: pointer;">
              Delete
            </button>
          </form>
        </div>
      </div>
    </article>
  {% endfor %}

  <!-- Pagination -->
  <div class="pagination">
    <span class="step-links">
      {% if page_obj.has_previous %}
        <a href="?page=1{% if tag_name %}&tag={{ tag_name }}{% endif %}">&laquo; first</a>
        <a href="?page={{ page_obj.previous_page_number }}{% if tag_name %}&tag={{ tag_name }}{% endif %}">previous</a>
      {% endif %}

      <span class="current">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
      </span>

      {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}{% if tag_name %}&tag={{ tag_name }}{% endif %}">next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}{% if tag_name %}&tag={{ tag_name }}{% endif %}">last &raquo;</a>
      {% endif %}
    </span>
  </div>

{% else %}
  <p>You haven't published any blog posts yet.</p>
{% endif %}
{% endblock %}